name: Check Update and Upload Releases

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Fetch all channel info
        run: python fetch.py

      - name: Process all channels
        run: |
          channels=("stable" "beta" "dev" "canary")
          arch="x64"

          for channel in "${channels[@]}"; do
            key="msedge-${channel}-win-${arch}"
            version=$(jq -r --arg k "$key" '.[$k].version' data.json)
            tag="${channel}-${arch}-${version}"
            zip="edge-${channel}-${arch}-${version}.zip"

            echo "==== $channel ===="
            echo "Version: $version"

            if git rev-parse "refs/tags/${tag}" >/dev/null 2>&1; then
              echo "Tag $tag exists, skipping..."
              continue
            fi

            url=$(jq -r --arg k "$key" '.[$k]["下载链接"]' data.json)
            curl -L "$url" -o "$zip"

            gh release create "$tag" "$zip" \
              --title "$tag" \
              --notes "Auto release for $channel $version"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
