name: Check Update and Upload Releases

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # chạy mỗi giờ

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set branches
        run: |
          echo "channels=stable beta dev canary" >> $GITHUB_ENV

      - name: Check and Process each channel
        run: |
          for channel in $channels; do
            echo "==== Checking $channel ===="
            
            # Lấy version mới nhất cho channel (python fetch.py trả về JSON hoặc text)
            version=$(python fetch.py --channel $channel)
            echo "Found version: $version"

            tag_name="${channel}-x64-${version}"
            zip_name="edge-${channel}-x64-${version}.zip"

            if git rev-parse "refs/tags/${tag_name}" >/dev/null 2>&1; then
              echo "Tag $tag_name exists, skip..."
              continue
            fi

            # Download file
            python download.py --channel $channel --arch x64 --output "$zip_name"

            # Upload release
            gh release create "$tag_name" "$zip_name" \
              --title "$tag_name" \
              --notes "Auto release for $channel channel version $version"

          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
